version: '3.8'

services:
  catalogdb:
    container_name: catalogdb
    ports:
      - "27017:27017"
    restart: always

  redisdb:
    container_name: basketdb
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    ports:
      - "8001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings:ConnectionString=redisdb:6379
    depends_on:
      - redisdb
    

